export const terminalHome = [
	{
		type: "typewriter",

		prompt: true,
		text: "pnpm create next-app",
		order: 0,
		title: "Creando el proyecto",
		description: [
			"<p>Este comando inicia la creación de un nuevo proyecto Next.js utilizando `pnpm`, una alternativa rápida y moderna a `npm` o `yarn`.</p>",
			"<p>Al ejecutarlo, se lanza un asistente interactivo que te guía a través de una serie de opciones para personalizar tu aplicación desde cero.</p>",
		],
	},
	{
		type: "input",
		title: "Nombre del proyecto",
		text: "What is your project named?",
		name: "appname",
		selected: "my-app",
		placeholder: "my-app",
		complete: false,
		order: 1,

		description: [
			"<p>Esta opción define el nombre del proyecto, que también será el nombre de la carpeta donde se generarán los archivos iniciales.</p>",
			"<p>Es recomendable usar un nombre corto, descriptivo y sin espacios, ya que puede utilizarse también como nombre del repositorio o en rutas de despliegue.</p>",
		],
	},
	{
		type: "select",
		title: "TypeScript",
		text: "Would you like to use <blue>TypeScript</blue>?",
		name: "typescript",
		options: ["No", "Yes"],
		selected: 0,
		order: 2,
		complete: false,
		description: [
			"<p>TypeScript es un superset de JavaScript que añade tipado estático, ayudando a detectar errores durante el desarrollo.</p>",
			"<p>Si eliges 'Yes', el proyecto se configurará automáticamente para trabajar con archivos `.ts` y `.tsx`, mejorando la robustez del código.</p>",
		],
	},
	{
		type: "select",
		title: "ESLint",
		text: "Would you like to use <blue>ESLint</blue>?",
		name: "eslint",
		options: ["No", "Yes"],
		selected: 1,
		order: 3,
		complete: false,
		description: [
			"<p>ESLint es una herramienta que analiza tu código en busca de errores y malas prácticas, ayudándote a mantener un estilo de código consistente.</p>",
			"<p>Activarlo desde el inicio permite integrar reglas de linting que mejoran la calidad del código y evitan errores comunes.</p>",
		],
	},
	{
		type: "select",
		title: "Tailwind CSS",
		text: "Would you like to use <blue>Tailwind CSS</blue>?",
		name: "tailwind",
		options: ["No", "Yes"],
		selected: 1,
		order: 4,
		complete: false,
		description: [
			"<p>Tailwind CSS es un framework de estilos basado en utilidades que permite crear interfaces rápidas y altamente personalizables.</p>",
			"<p>Elegir esta opción configura automáticamente Tailwind en tu proyecto, ahorrándote la instalación y configuración manual.</p>",
		],
	},
	{
		type: "select",
		title: "Directorio src",
		text: "Would you like your code inside a <blue>`src/` directory</blue>?",
		name: "src",
		options: ["No", "Yes"],
		selected: 1,
		order: 5,
		complete: false,
		description: [
			"<p>Colocar el código fuente dentro de una carpeta `src/` ayuda a mantener una estructura de proyecto más limpia y organizada.</p>",
			"<p>Esta opción es especialmente útil en proyectos grandes, donde es importante separar claramente los archivos fuente del resto de la configuración.</p>",
		],
	},
	{
		type: "select",
		title: "App Router",
		text: "Would you like to use <blue>App Router</blue>? (recomended)",
		name: "approuter",
		lastText: "(recommended)",
		textName: "App Router",
		options: ["No", "Yes"],
		selected: 1,
		order: 6,
		complete: false,
		description: [
			"<p>El App Router es la nueva forma recomendada de manejar rutas en Next.js, ofreciendo funcionalidades como layouts anidados y manejo más flexible del estado.</p>",
			"<p>Seleccionar esta opción permite aprovechar las últimas mejoras en rendimiento y arquitectura introducidas por Next.js 13+.</p>",
		],
	},
	{
		type: "select",
		title: "Empaquetador TurboPack",
		name: "turbopack",
		text: "Would you like to use <blue>TurboPack</blue> for `next dev`?",
		options: ["No", "Yes"],
		selected: 1,
		order: 7,
		complete: false,
		description: [
			"<p>TurboPack es el nuevo empaquetador de código experimental para Next.js, diseñado para reemplazar Webpack con un rendimiento superior.</p>",
			"<p>Al usarlo en desarrollo (`next dev`), verás recargas más rápidas y mejor experiencia durante la edición de código.</p>",
		],
	},
	{
		type: "select",
		title: "Alias de importación",
		text: "Would you like to customize the <blue>import alias</blue> (`@/*` by default)?",
		name: "alias",
		options: ["No", "Yes"],
		selected: 1,
		order: 8,
		complete: false,
		description: [
			"<p>El alias de importación permite usar rutas más limpias y legibles al importar archivos, en lugar de rutas relativas largas como `../../components`.</p>",
			"<p>Personalizar el alias puede ayudarte a adaptarlo a tu estilo de organización o a otros estándares que ya uses en tu equipo o proyectos.</p>",
		],
	},
];
